"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.NewPluginCommand = exports.BuildPluginCommand = exports.BuildBundleCommand = void 0;
const tslib_1 = require("tslib");
const bundle_1 = tslib_1.__importDefault(require("./commands/build/bundle"));
exports.BuildBundleCommand = bundle_1.default;
const plugin_1 = tslib_1.__importDefault(require("./commands/build/plugin"));
exports.BuildPluginCommand = plugin_1.default;
const plugin_2 = tslib_1.__importDefault(require("./commands/new/plugin"));
exports.NewPluginCommand = plugin_2.default;
